blank_issues_enabled: false
contact_links:
  - name: Need help? Create a discussion post
    url: https://github.org/bountyhub-org/platform/discussions/new
    about: If you have a question or need help, create a discussion post.